sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
- openjdk8
branches:
  except:
  - www
cache:
  directories:
  - "$HOME/.gradle/caches/modules-2"
  - "$HOME/.gradle/caches/jars-1"
  - "$HOME/.gradle/wrapper"
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- git fetch --depth=10000 origin
- ./etc/decrypt-ssh-key.sh
- cp etc/gradle-ci.properties .
install:
- "./gradlew ciPrep --stacktrace"
script: "./gradlew ciTest --stacktrace"
after_failure:
- jps -lvm
after_success:
- bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f $HOME/.gradle/caches/*/*.lock
deploy:
  provider: script
  skip_cleanup: true
  script: etc/deploy.sh
  on:
    jdk: oraclejdk8
    repo: lenskit/lenskit
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
env:
  global:
  - TERM=dumb
  - TZ=CST6CDT
  - MALLOC_ARENA_MAX=2
  - "_JAVA_OPTIONS='-Xmx512m'"
  # SONAR_TOKEN
  - secure: "JSzx8Y50B4uPM5jYyED1d4LdlhxqG0pmGLnNfdHlxfwx3HWn7Trzlip2eNeVXor1OMbQxyDfzOLXjepfXY/lLB3FrmOdkEROy+WnZUBjMM55g+sOKskOzI3FbnKl09uf1hvprzij8UMImfZHgoQIbDgf2GpAmp1vskCVe7BDqsE="
  # SONATYPE_USER
  - secure: "KZlIPTwPJwh3mbsk4M98YnY+Jf7B0on5MVK4Q+0nKR6HJS9cn5zAmO5NU7ouLfl6/HCzD7YftqQEybuV3w1S5WM2CJvSe1yS5RDilQ0cFSx8QZe6xDprcFPawMfQ+DN3fEtqXieu8lVcqGtKL+JqF7piTmrN26ojCCdC6zpiy24="
  # SONATYPE_PASSWORD
  - secure: "JSZlPX3fbNrbUfBRcH6OdfQfAk65G3l1diJ4vxu/VvKGsH+eAOt6gfaKVNe8JRuPyyzmArgSK4QlM2lwvxKwgSEblw2hF1VDotJwHeD//NxTQBjeeOu3dV8BtsJE7kxT66ywyLai5jcGxLgFgWEEiA1ZwZjmBaZzn1rCwJVGKHk="
  # Coverity token
  - secure: "Bj66Sq92T/khNFGwMU4JYExlycwrkogdsf35GFeB4YiEC7bhrDsshpFWMWcQstUMo5+tJmTBCuXY6YHOHMUcjxjr+RFSuetwluzCumklJGHQms3s83peqle4E8Lu6b5Y1VKekf8Iri6P2+efI2fii5Pr0BD1RozPdBCQfZGqQYc="
